[workspace]
members = [
    "programs/*"
]
resolver = "2"

[profile.release]
overflow-checks = true # Prevent integer overflow attacks
lto = "fat" #Link-time optimization for smaller binary
codegen-units = 1

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
